### ISSUE TITLE
Scheduler Task t3monitoring:monitoring:importclients fails

### ISSUE THREAD

**Issue by marteb** [georgringer/t3monitoring#125]
The error message is:

`Execution of task "Extbase CommandController Task (extbase)" failed with the following message: The given alias 'tx_t3monitoring_domain_model_extension' is not unique in FROM and JOIN clause table. The currently registered aliases are: 'tx_t3monitoring_client_extension_mm', 'tx_t3monitoring_domain_model_extension'.`

Environment:

TYPO3 8.7.13
PHP 7.1.15

**Comment by georgringer** [comment]
Fixed with https://github.com/georgringer/t3monitoring/pull/121
