### ISSUE TITLE
Update of extension list fails

### ISSUE THREAD

**Issue by peterkraume** [georgringer/t3monitoring#126]
`#1342635378: Could not write to file /path/to/t3monitoring/var/extensionmanager/1.mirrors.xml.gz.`

It seems not to be an issue about file permissions because I even did a `chmod -R 777` on  the `var` folder. `var/extensionmanager` exists.

The error occurs on every possibility to update the extension list:
- t3monitor backend module
- scheduler task
- running the command controller from command line via EXT:typo3_console

Tested with latest Git master of EXT:t3monitoring and TYPO3 9.2.
TYPO3 is in composer mode.

Maybe the issue is that the `var` folder is outside my document root?

This is my folder structure:
```
composer.json
composer.lock
.git
.gitignore
typo3cms -> vendor/helhum/typo3-console/typo3cms
var
vendor
web
```

`web` is the document root.

**Comment by georgringer** [comment]
I guess not an issue anymore?

**Comment by peterkraume** [comment]
Currently I can't reproduce this issue. Closed :)
