### ISSUE TITLE
TYPO3 Deprecation Notice: Tagging properties with @lazy is deprecated

### ISSUE THREAD

**Issue by peterkraume** [georgringer/t3monitoring#127]
`Core: Error handler (BE): TYPO3 Deprecation Notice: Tagging properties with @lazy is deprecated and will be removed in TYPO3 v10.0. in /path/to/t3monitoring/web/typo3/sysext/extbase/Classes/Reflection/ClassSchema.php line 223`

Tested with TYPO3 9.2 and latest Git master of EXT:t3monitoring

Affected file:
t3monitoring/Classes/Domain/Model/Client.php
Lines: 120, 126, 132, 138

**Comment by georgringer** [comment]
only 8 is supported
