### ISSUE TITLE
TYPO3 Deprecation Notice: Request headers as colon-separated string are deprecated, use an associative array instead.

### ISSUE THREAD

**Issue by peterkraume** [georgringer/t3monitoring#128]
`TYPO3 Deprecation Notice: Request headers as colon-separated string are deprecated, use an associative array instead. in /path/to/t3monitoring/web/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1805`

Tested with TYPO3 9.2 and latest Git master of EXT:t3monitoring

This deprecation message occurs when I update the client list.

**Comment by josefglatz** [comment]
@peterkraume can u still reproduce this with 9.5 LTS? I can't reproduce it actually.

**Comment by josefglatz** [comment]
I'm sure we can close this issue as I switched to the `RequestFactory` instead of using the getUrl method of `GeneralUtility::class`.
