### ISSUE TITLE
TYPO3 Deprecation Notice: Tagging methods with @ignorevalidation is deprecated

### ISSUE THREAD

**Issue by peterkraume** [georgringer/t3monitoring#129]
`TYPO3 Deprecation Notice
Core: Error handler (BE): TYPO3 Deprecation Notice: Tagging methods with @ignorevalidation is deprecated and will be removed in TYPO3 v10.0. in /path/to/t3monitoring/web/typo3/sysext/extbase/Classes/Reflection/ClassSchema.php line 347`

Tested with TYPO3 9.2 and latest Git master of EXT:t3monitoring

This message occurs when I view the client detail page.

**Comment by georgringer** [comment]
yes but IMO I can't support at this place 8+9
