### ISSUE TITLE
„Insecure Core“ after updating clients to latest typo3 core

### ISSUE THREAD

**Issue by marteb** [georgringer/t3monitoring#130]
Updating clients to latest typo3/cms 8.7.15 leads to warning: „Insecure Core“.
Scheduler Tasks „import core“ and „import clients“ both were successfully finished.

Is this a problem of t3monitor or the source where it imports the information about „secure“ core versions from?

**Comment by marteb** [comment]
I tried to debug this today. There was an entry for 8.7.15 in the tx_t3monitoring_domain_model_core table, but the fields 'release_date', 'latest', 'stable', 'is_stable', 'is_active', ' is_latest', 'is_official' and 'crdate' were empty or 0. And the field 'insecure' was set to 1.

Maybe the data was imported once wrong or the import didn’t finish for the first time when 8.7.15 was released. But the problem here seems to be, that this data seems not to be updated when there are changes.

**Comment by georgringer** [comment]
I fixed some things, so I am closing this issue
