### ISSUE TITLE
Task coreImport won't update existing cores in 2.0.0

### ISSUE THREAD

**Issue by timhorstmann** [georgringer/t3monitoring#135]
After upgrading t3monitoring from version 1.0.1 to version 2.0.0, existing cores in the database won't get updated when running the scheduler.

Problem is in Class Service\Import\CoreImport line 65. Code is

`$connection->update(`
`  $table,
`  [
`    'tstamp' => $GLOBALS['EXEC_TIME'],
`    'pid' => $this->emConfiguration->getPid()
`  ],
`  [
`    'uid' => $previousCoreVersions[$version]['uid']
`  ]
`);

and should be

`$connection->update(
`  $table,
`                        $item,
`                        [
`                            'uid' => $previousCoreVersions[$version]['uid']
`                        ]
`                    );

I think this was overseen when refactoring from 1.0.1 to 2.0.0.
Sorry for my codeformating.

**Comment by timhorstmann** [comment]
@georgringer Travis builds are failing for quite a while and for other pull requests too. And it doesn't seem to be caused by the code chances. Can you provide some background, what is going wrong and wether the pull requests can be merged anyway?

**Comment by georgringer** [comment]
fixed
