### ISSUE TITLE
Outdated Core

### ISSUE THREAD

**Issue by jousch** [georgringer/t3monitoring#14]

**Comment by georgringer** [comment]
It shows outdated cores?!

**Comment by jousch** [comment]
4.7.x isn't marked as outdated

**Comment by georgringer** [comment]
![image](https://cloud.githubusercontent.com/assets/1905663/14097928/1b25d298-f577-11e5-858f-78a2b147571b.png)
marked insecure for me ...

**Comment by jousch** [comment]
Actually 4.7.20 is only marked insecure. It must also be marked outdated.

_@georgringer, you see it in our internal test monitoring instance_
