### ISSUE TITLE
Not applicable extension version recommended for upgrade

### ISSUE THREAD

**Issue by griesi007** [georgringer/t3monitoring#145]
I am using Typo3 8.7.24 with gridelements 8.3.0 (non composer installation). t3monitoring lists for example gridelements 9.0.0 as available upgrade . But gridelements 9 does not support Typo3 8.x. same with imageoptimizer 2.0.0 and others

![25-01-_2019_09-35-55](https://user-images.githubusercontent.com/2854973/51734836-00a48800-2086-11e9-9ffc-9efa24ecc466.jpg)

**Comment by georgringer** [comment]
this will be one of the next features. the reason why I did this is because previously it often worked even though it was stated differently

**Comment by georgringer** [comment]
solved now
