### ISSUE TITLE
Extension Configuration Button is not working on TYPO3 9

### ISSUE THREAD

**Issue by schugabe** [georgringer/t3monitoring#156]
Clicking the button yields the exception `Class TYPO3\CMS\Extensionmanager\Controller\ConfigurationController does not exist. Reflection failed.`

**Comment by josefglatz** [comment]
@schugabe Please can you give more infos which configuration button you mean?

**Comment by schugabe** [comment]
![image](https://user-images.githubusercontent.com/138686/64940459-52dc2880-d864-11e9-813c-4c6096cd2fc1.png)
I marked it in the screenshot

**Comment by josefglatz** [comment]
@schugabe @georgringer @liayn  I think it is actually not possible to link directly to the extConf wizard of an extension?

**Comment by liayn** [comment]
Correct, there is no deep-link possibility in the Install Tool. So lets remove the button in the UI?

**Comment by georgringer** [comment]
Yes pls remove
