### ISSUE TITLE
Current TYPO3 Version 8.7.32 is marked as insecure

### ISSUE THREAD

**Issue by Starraider** [georgringer/t3monitoring#175]
The current TYPO3 Version 8.7.32 is marked as insecure, but as far as I know that's not true.
![screenshot](https://user-images.githubusercontent.com/279975/78634551-d3767b00-78c1-11ea-908a-45e6a6926bbf.jpg)

**Comment by maslme** [comment]
Same here with the TYPO3 8.7 ELTS version - actually 8.7.38.

**Comment by georgringer** [comment]
all non active versions are marked as insecure becuase there the security team does *not* cover those versions. so it can be that there are security issues - not only the ones which are e.g. fixed in 9/10/11 but also new ones because of outdated code.

outdated means insecure

**Comment by maslme** [comment]
Than you should call it "outdated" and not insecure. Insecure is for me a version, when a vulnerability is known, and not only when it could be.
