### ISSUE TITLE
Namespace Backend UriBuilder Error

### ISSUE THREAD

**Issue by wrock** [georgringer/t3monitoring#178]
Hi, 

du hast in der neuen Version für T3 10 in /Classes/Controller/BaseController.php, Zeile 165 irrtümlich 
 $uriBuilder = GeneralUtility::makeInstance(UriBuilder::class);   
statt  
 $uriBuilder = GeneralUtility::makeInstance(\TYPO3\CMS\Backend\Routing\UriBuilder::class);
Somit wird der UriBuilder aus dem use genommen.

Liebe Grüße,
Wolfgang

**Comment by josefglatz** [comment]
Hey Wolfgang! Can you create a PR, please?

**Comment by georgringer** [comment]
fixed with https://github.com/georgringer/t3monitoring/commit/faa3723430dab2d3e977542a730535b421d5a3f0#diff-ad6d09905d5f6451c68bf3f79eef820a7cfa47fa1ad63e3ba8a1e916d3249782 long time ago
