### ISSUE TITLE
"List all" throughs exception https://wiki.typo3.org/Exception/CMS/1297759968

### ISSUE THREAD

**Issue by jousch** [georgringer/t3monitoring#18]
> #1297759968: Exception while property mapping at property path "": Property "withExtraWarning" was not found in target object of type "T3Monitor\T3monitoring\Domain\Model\Dto\ClientFilterDemand". (More information)

> TYPO3\CMS\Extbase\Property\Exception thrown in file
/html/typo3-t3monitoring/typo3_src-7.6.4/typo3/sysext/extbase/Classes/Property/PropertyMapper.php in line 128.

(Actual git master when I was creating this issue)

**Comment by jousch** [comment]
Error occurs also, when I fire up the search form on the home page of the backend module

**Comment by georgringer** [comment]
@jousch DB compare and system cache cleared?

**Comment by georgringer** [comment]
fixed after clearing system cache
