### ISSUE TITLE
Error thrown when accessing t3monitoring BE module

### ISSUE THREAD

**Issue by NairCoder** [georgringer/t3monitoring#180]
**Setup Configuration**
TYPO3 -- v10.4
t3monitoring -- v2.0.0
PHP -- v7.2

**Issue**
Installed t3monitoring in a fresh instance and added few clients. When trying to access the BE module, an error in thrown from ext/t3monitoring/Classes/Controller/BaseController.php, Line no. 168. 

![Screenshot 2020-04-23 at 17 08 13](https://user-images.githubusercontent.com/59689476/80116081-d0e47880-8585-11ea-86eb-8b26999efd04.png)

**Cause**
A backend module URL is trying to be built, with function buildUriFromRoute.
TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder doesn't have buildUriFromRoute anymore. But the same function can be called from \TYPO3\CMS\Backend\Routing\UriBuilder.
There are totally 3 calls to the same function in BaseController.php

**Fix**
```
$backendUriBuilder = GeneralUtility::makeInstance(\TYPO3\CMS\Backend\Routing\UriBuilder::class);

// Buttons for new records
$returnUrl = rawurlencode($backendUriBuilder->buildUriFromRoute('tools_T3monitoringT3monitor', [
    'tx_t3monitoring_tools_t3monitoringt3monitor' => [
        'action' => $this->request->getControllerActionName(),
        'controller' => $this->request->getControllerName()
    ]
]));
```

**Comment by jacobsenj** [comment]
Duplicate to #178
