### ISSUE TITLE
[BUG] monitoring:importAll command returns status code NULL

### ISSUE THREAD

**Issue by TheJotob** [georgringer/t3monitoring#183]
If i run the console command monitoring:importAll in the scheduler I get a "failure" flag on it, because the command returns the status code "NULL" instead of 0. So TYPO3 thinks there is an error, eventhough it is all working perfectly.
This should be changed to return the correct error code.

**Comment by peterkraume** [comment]
This problem is related to https://forge.typo3.org/issues/90032

**Comment by josefglatz** [comment]
@peterkraume can this issue be closed?

**Comment by peterkraume** [comment]
Yes
