### ISSUE TITLE
importExtensions has a long runtime

### ISSUE THREAD

**Issue by ghost** [georgringer/t3monitoring#189]
Hello,

the process 'importExtensions' unfortunately takes too long and is killed by our hoster after about 15 minutes.

If I run the scheduler by hand, it will be aborted as well. I have no hints in the PHP log nor in the output.

I use the following version of T3Monitoring: https://github.com/georgringer/t3monitoring/tree/faa3723430dab2d3e977542a730535b421d5a3f0

Unfortunately I don't really have much information about it. I would be grateful for any advice on how to debug the problem.

The schedulers for 'importCore' and 'importClients' work as expected.

Thanks for the support.

PHP 7.2.29
cURL Information 7.64.0
SSL Version OpenSSL/1.1.1b

**Comment by christophlehmann** [comment]
I'm not 100% sure, but if i remind correct it's only the first import which takes so long. Maybe you can run it locally first and use the table data.

**Comment by georgringer** [comment]
it triggers the extension manager extension download, nothing I can really do here
