### ISSUE TITLE
How about an field for "update info" in dataset of the instances?

### ISSUE THREAD

**Issue by kanow** [georgringer/t3monitoring#190]
We had often different environments for single instances. I would prefer an additional database field for useful informations about that instance. I'm not sure about the details of implementation of this feature. Maybe someone has ideas.

What do you think about this feature? A chance to get in or should I use an own extension to extend t3monitoring?

**Comment by maslme** [comment]
I think this is a good feature. I would use it in an littlebit different way - some of my customers would like to be informed about an update, some not - so I can mark them as they would and get the informations for them.

**Comment by georgringer** [comment]
I currently use tags for that or just add `[DEV]` in the title

**Comment by kanow** [comment]
Ok, I will think about this tags model.
