### ISSUE TITLE
Relative path to jquery.dataTables.min.js library

### ISSUE THREAD

**Issue by instruccionesaldorso** [georgringer/t3monitoring#198]
Using master version, I experience that, when BE module "T3 Monitor" is called, the next JavaScript error happens over the console:

GET https://example.com/typo3/typo3conf/ext/t3monitoring/Resources/Public/JavaScript/jquery.dataTables.min.js?bust=1631690811 net::ERR_ABORTED 404

It seems the relative path to the file adds "typo3" as the JavaScript should be loaded over the BE and relative path is related to "typo3/" url instead of being absolute and reference to the project root public folder.

Isn't it possible that these lines:

https://github.com/georgringer/t3monitoring/blob/master/Classes/Controller/BaseController.php#L91
https://github.com/georgringer/t3monitoring/blob/master/Classes/Controller/BaseController.php#L92

should add "/" at the beginning of the string, before $fullJsPath ?

**Comment by hoermannklaus** [comment]
I also encountered the same error. Due to this error it is not possible to sort the backend table of all clients. With your fix the DataTable library gets loaded correctly again, and sorting the clients is possible again. 
How about making a PR?
