### ISSUE TITLE
TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by christophlehmann** [georgringer/t3monitoring#203]
I created the branch 11-compatibility for it.

**Comment by instruccionesaldorso** [comment]
We're trying this new git branch to solve this issue https://github.com/georgringer/t3monitoring/issues/198 and don't patch the extension, but we receive another error when we try to access the "T3 Monitor" module:

Call to a member function isEnvironmentInFrontendMode() on null
in /var/www/html/public/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php line 610

Could you take a look? We just use 10.4.
We understand support for 10.4 is not dropped over "11-compatibility" branch, right?

**Comment by instruccionesaldorso** [comment]
@christophlehmann Could you take a look to this issue?
I just saw yesterday you merged v11 compatibility into "master" branch and I updated our composer package against "master".
However, this issue is still happening over a v10.4 instance.

**Comment by christophlehmann** [comment]
When you are able to sponsor a Bugfix for your issue, then please contact Georg, he offers paid support ;)

**Comment by georgringer** [comment]
master is now compatible

**Comment by tbsschmdt** [comment]
Introduction of TYPO3 11 compatibility unfortunately broke TYPO3 10 compatibility. You could run `composer require t3monitor/t3monitoring:dev-master#b463f426fe18a8d5e98d7ba63e67501aba852584` to use the latest version that works with TYPO3 10, @instruccionesaldorso.

> @christophlehmann Could you take a look to this issue? I just saw yesterday you merged v11 compatibility into "master" branch and I updated our composer package against "master". However, this issue is still happening over a v10.4 instance.
