### ISSUE TITLE
TYPO3 10 compatibility is broken

### ISSUE THREAD

**Issue by tbsschmdt** [georgringer/t3monitoring#207]
Introduction of TYPO3 11 compatibility unfortunately broke TYPO3 10 compatibility. This should either be fixed or requirements in _composer.json_ and _ext_emconf.php_ should be updated.

(Run `composer require t3monitor/t3monitoring:dev-master#b463f426fe18a8d5e98d7ba63e67501aba852584` to use the latest version that works with TYPO3 10.)

**Comment by georgringer** [comment]
I am currently working on the extension and I am not yet sure if I will keep it compatible with both versions - I guess not. if a release is still missing, i will do one before
