### ISSUE TITLE
Add comment field to tx_t3monitoring_domain_model_client

### ISSUE THREAD

**Issue by mueller-sebastian** [georgringer/t3monitoring#218]
Hi there,

thank you for this nice extension. While working with it, we've got the need for the possibility to add a comment to a client so we can add some additional information there. This comment could be shown near (or in) the "Facts" section in the client detail view.

Is there a reason why there is no such field (you explicitly do not want it) or just the lack of need/time until now?

Would you prefer us sponsoring this feature or getting an pull request?

Greetings
Sebastian

**Comment by georgringer** [comment]
hey! thanks for creating the issue! a pr would be really fine + enough. thx. if you got no time at all, free to contact me in private for sponsoring this little thing
