### ISSUE TITLE
Currently no TYPO3 v11 possible? 

### ISSUE THREAD

**Issue by woodyc79** [georgringer/t3monitoring#230]
It seems that currently there is no version of t3monitor/t3monitoring that works with T3v11 any more? In the last months I could use dev-master - but this now also requires v12

**Comment by jacobsenj** [comment]
You can use a commit hash from before the TYPO3 12 Update commit in the meantime.

**Comment by georgringer** [comment]
yes, monitoring is switching to v12 ;)
