### ISSUE TITLE
Exception while property mapping at property path

### ISSUE THREAD

**Issue by peterkraume** [georgringer/t3monitoring#31]
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1297759968: Exception while property mapping at property path "": The identity property "Array" is no UID. | TYPO3\CMS\Extbase\Property\Exception thrown in file /SOMEPATH/t3monitoring/vendor/typo3/cms/typo3/sysext/extbase/Classes/Property/PropertyMapper.php in line 128. Requested URL: http://DOMAIN.TLD/typo3/index.php?M=tools_T3monitoringT3monitor&moduleToken=c9d9773f3a121b328497d06010e53b22e5fb8677&tx_t3monitoring_tools_t3monitoringt3monitor[action]=index&tx_t3monitoring_tools_t3monitoringt3monitor[controller]=Statistic&tx_t3monitoring_tools_t3monitoringt3monitor[__referrer]=Array&tx_t3monitoring_tools_t3monitoringt3monitor[__trustedProperties]=a:1:{s:6:%22filter%22;a:10:{s:16:%22withExtraWarning%22;i:1;s:15:%22withExtraDanger%22;i:1;s:10:%22searchWord%22;i:1;s:7:%22version%22;i:1;s:3:%22sla%22;i:1;s:16:%22withInsecureCore%22;i:1;s:16:%22withOutdatedCore%22;i:1;s:22:%22withOutdatedExtensions%22;i:1;s:22:%22withInsecureExtensions%22;i:1;s:16:%22withErrorMessage%22;i:1;}}060a74d6cd5d4cd3a1b1f0b97abdcf1ce3226328&tx_t3monitoring_tools_t3monitoringt3monitor[filter]=Array`

This happens when I edit a client record within the T3 Monitor Backend Module and then hit "close" or "save and close".

TYPO3: 7.6.5
t3monitoring: latest dev-master

**Comment by liayn** [comment]
confirmed

**Comment by georgringer** [comment]
fixed now, thx to @liayn
