### ISSUE TITLE
fetching security bulletins is not proxy-aware

### ISSUE THREAD

**Issue by ajindra** [georgringer/t3monitoring#53]
Security bulletins can't be fetched if the server is behind a proxy, thus leading to a time out upon trying and in consequence leaving the t3monitoring main screen unusable.

**Comment by georgringer** [comment]
You can disable it in the extension manager

**Comment by ajindra** [comment]
Well, I thought of something that would make the rss import possible, like
```php
      $proxy = …; 
      if (strlen($proxy) > 1) { 
        $r_default_context = stream_context_get_default ( array 
                    ('http' => array( 
                        'proxy' => $proxy, 
                        'request_fulluri' => true, 
                    ), 
                ) 
            ); 
        libxml_set_streams_context($r_default_context); 
      }
```

right before the rss->load() but I understand if you think it's not worth the effort.
