### ISSUE TITLE
Special chars in extension author string break complete data collection

### ISSUE THREAD

**Issue by andre-spindler** [georgringer/t3monitoring#76]
One of the sites (6.2) I check does not return any data when t3monitoring collects its data.

After some debugging I found out that this is caused by one of the extensions.
Fetching data works, but converting the data array to json fails and returns an empty string then.
This is caused by the extension "libunzipped", version 2.1.0.
Ok this extension is old, but it remains in this installation since the original setup with TYPO3 4.0 in 2006.
Error is caused by the author of the extensions, and extension author is our well known fathof TYPO3, Kasper Skårhøj. And his name breaks the request...

**Comment by beathorst** [comment]
this is fixed in the t3monitoring_client with this pull-request https://github.com/georgringer/t3monitoring_client/pull/28
