### ISSUE TITLE
Password last changed

### ISSUE THREAD

**Issue by garbast** [georgringer/t3monitoring#8]
A check if password was last changed for each user would be nice.

**Comment by jousch** [comment]
Do we need here a new field `lastchangedpassword` like `lastlogin`?

**Comment by garbast** [comment]
Good question. As im coming for installation that are all using ext:be_secure_pw we als ways habe tx_besecurepw_lastpwchange, that why i didnt thought about that.

So you are right we need some kind of field that stores this value. Maybe this test should only be provided in case the extension is installed or not.

**Comment by georgringer** [comment]
see https://github.com/georgringer/t3monitoring_client/blob/master/Classes/Provider/DummyDataProvider.php#L23-L25 how a provider could look like. not planning to implement that currently.

IMO this is highly dependent on the contracts and requirements of the customer and can't be done globally. I don't change my passwords but still those are very secure.

**Comment by garbast** [comment]
I agree thats very specific, so if it's possible to register own tests server- and client-side it's totaly fine. Thanks for hinting at the Dummy.
