### ISSUE TITLE
[Feature] Show Disk Space and Free Disk Space

### ISSUE THREAD

**Issue by beathorst** [georgringer/t3monitoring#89]
It would be niche to have the Free Disk Space of the Server in the overview of an Client
I did it for our fork and would make an pull-request if you wish

<img width="604" alt="bildschirmfoto 2017-09-29 um 19 40 33" src="https://user-images.githubusercontent.com/212705/31028431-3ea2cf54-a54e-11e7-893d-cb99642d1c66.png">

**Comment by georgringer** [comment]
yeah please go ahead
